# This is a basic workflow to help you get started with Actions

name: Remove aliyun oss files after delete

on:
  delete:
    branches-ignore:
      - 'master'
    tags:
      - 'not-exists'
  

jobs:

  remove_files:
    runs-on: ubuntu-latest
    steps:
      - name: download ossutil
        run: wget https://gosspublic.alicdn.com/ossutil/1.4.2/ossutil64
      - name: remove ${{ github.event.ref }} files
        run: echo ${{ github.event.ref }}
