# This is a basic workflow to help you get started with Actions

name: Remove aliyun oss files after delete

on: delete

jobs:
  remove_files:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: download ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.4.2/ossutil64
          chmod a+x ./ossutil64
      - name: setup ossutil environment variables
        run: ./ossutil64 config -e "${{ secrets.OssEndPoint }}" -i "${{ secrets.OssAppKeyId }}" -k "${{ secrets.OssAppKeySecret }}"
      - name: remove ${{ github.event.ref }} files
        run: ./ossutil64 rm oss://${{ secrets.OssBucket }}/${{ github.event.ref }} --recursive --force --all-type
